In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5]

In [3]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [7]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [8]:
np.ones((3,3,6))

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

In [9]:
5+np.zeros((3,4)) #broadcasting

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [11]:
np.empty((5,4,5))

array([[[1.81363726e-152, 4.26954078e+257, 1.09944918e+155,
         3.04284970e+169, 9.09157492e+223],
        [3.17095864e+180, 6.96411093e+252, 3.03772868e-067,
         1.90327826e+185, 7.22937202e+159],
        [2.07826338e+156, 2.16209963e+233, 6.37268227e+270,
         8.01767884e-096, 1.01159630e-153],
        [1.46922886e+195, 2.39292253e-258, 1.12547024e-153,
         3.06209003e+169, 3.05196288e+169]],

       [[3.05196290e+169, 3.02890637e-086, 2.47877538e-070,
         2.47877538e-070, 2.47877538e-070],
        [2.66054070e-260, 1.21906099e-152, 7.19210710e+252,
         1.49345442e+214, 4.95261614e+223],
        [2.30224366e+262, 1.06167117e-153, 9.77080316e-153,
         1.27587193e-152, 3.80985995e+180],
        [1.96393284e-152, 6.02669629e+175, 5.81948492e+199,
         3.15091948e+161, 8.78414022e+247]],

       [[1.69803111e-152, 1.67494825e+243, 3.59535131e+246,
         2.46598538e-154, 9.78567885e+199],
        [8.70657824e+183, 1.32882766e+179, 4.82406565e+228,


In [19]:
np.linspace(2,6,10).reshape(5,2)

array([[2.        , 2.44444444],
       [2.88888889, 3.33333333],
       [3.77777778, 4.22222222],
       [4.66666667, 5.11111111],
       [5.55555556, 6.        ]])

In [21]:
np.logspace(2,4,10,base=10)

array([  100.        ,   166.81005372,   278.25594022,   464.15888336,
         774.26368268,  1291.54966501,  2154.43469003,  3593.8136638 ,
        5994.84250319, 10000.        ])

In [43]:
a=np.arange(4,40).reshape(6,6)

In [44]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [46]:
a.max(axis=0)

array([34, 35, 36, 37, 38, 39])

In [47]:
a.max(axis=1)

array([ 9, 15, 21, 27, 33, 39])

In [48]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [49]:
10+a

array([[14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37],
       [38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49]])

In [50]:
a/0

C:\Users\Harshith D\AppData\Local\Temp/ipykernel_16888/4102073204.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a/0


array([[inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf]])

In [51]:
a**2

array([[  16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225],
       [ 256,  289,  324,  361,  400,  441],
       [ 484,  529,  576,  625,  676,  729],
       [ 784,  841,  900,  961, 1024, 1089],
       [1156, 1225, 1296, 1369, 1444, 1521]], dtype=int32)

In [52]:
pow(a,2)

array([[  16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225],
       [ 256,  289,  324,  361,  400,  441],
       [ 484,  529,  576,  625,  676,  729],
       [ 784,  841,  900,  961, 1024, 1089],
       [1156, 1225, 1296, 1369, 1444, 1521]], dtype=int32)

In [53]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [58]:
b=np.array([2,3,1,2,3,2])

In [59]:
a+b

array([[ 6,  8,  7,  9, 11, 11],
       [12, 14, 13, 15, 17, 17],
       [18, 20, 19, 21, 23, 23],
       [24, 26, 25, 27, 29, 29],
       [30, 32, 31, 33, 35, 35],
       [36, 38, 37, 39, 41, 41]])

In [64]:
b

array([2, 3, 1, 2, 3, 2])

In [65]:
b=b.reshape(1,-1)

In [66]:
b

array([[2, 3, 1, 2, 3, 2]])

In [67]:
b=b.T

In [68]:
b

array([[2],
       [3],
       [1],
       [2],
       [3],
       [2]])

In [69]:
a+b

array([[ 6,  7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17, 18],
       [17, 18, 19, 20, 21, 22],
       [24, 25, 26, 27, 28, 29],
       [31, 32, 33, 34, 35, 36],
       [36, 37, 38, 39, 40, 41]])

In [70]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [71]:
np.sqrt(a)

array([[2.        , 2.23606798, 2.44948974, 2.64575131, 2.82842712,
        3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
        3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
        4.58257569],
       [4.69041576, 4.79583152, 4.89897949, 5.        , 5.09901951,
        5.19615242],
       [5.29150262, 5.38516481, 5.47722558, 5.56776436, 5.65685425,
        5.74456265],
       [5.83095189, 5.91607978, 6.        , 6.08276253, 6.164414  ,
        6.244998  ]])

In [72]:
np.exp(a)

array([[5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
        2.98095799e+03, 8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
        1.20260428e+06, 3.26901737e+06],
       [8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
        4.85165195e+08, 1.31881573e+09],
       [3.58491285e+09, 9.74480345e+09, 2.64891221e+10, 7.20048993e+10,
        1.95729609e+11, 5.32048241e+11],
       [1.44625706e+12, 3.93133430e+12, 1.06864746e+13, 2.90488497e+13,
        7.89629602e+13, 2.14643580e+14],
       [5.83461743e+14, 1.58601345e+15, 4.31123155e+15, 1.17191424e+16,
        3.18559318e+16, 8.65934004e+16]])

In [73]:
np.log10(a)

array([[0.60205999, 0.69897   , 0.77815125, 0.84509804, 0.90308999,
        0.95424251],
       [1.        , 1.04139269, 1.07918125, 1.11394335, 1.14612804,
        1.17609126],
       [1.20411998, 1.23044892, 1.25527251, 1.2787536 , 1.30103   ,
        1.32221929],
       [1.34242268, 1.36172784, 1.38021124, 1.39794001, 1.41497335,
        1.43136376],
       [1.44715803, 1.462398  , 1.47712125, 1.49136169, 1.50514998,
        1.51851394],
       [1.53147892, 1.54406804, 1.5563025 , 1.56820172, 1.5797836 ,
        1.59106461]])

In [74]:
x = np.array([1,2,3])

In [75]:
y=x #shallow copy

In [76]:
y

array([1, 2, 3])

In [77]:
z = np.copy(x) #deep copy

In [78]:
z

array([1, 2, 3])

In [79]:
x[0]=100

In [80]:
y

array([100,   2,   3])

In [81]:
z

array([1, 2, 3])

In [82]:
id(z)

1461925209072

In [83]:
id(y)

1461925208304

In [84]:
id(x)

1461925208304

In [85]:
x

array([100,   2,   3])

In [86]:
id(x[0])

1461925201200

In [87]:
id(y[0])

1461925203088

In [88]:
su = np.array([567,345])

In [89]:
df = su

In [90]:
id(su)

1461925210512

In [91]:
id(df)

1461925210512

In [92]:
id(su[0])

1461925203568

In [93]:
id(df[0])

1461925203152

In [94]:
id(su[0]) == id(df[0])

True

In [95]:
xt = np.array([34,67,89])

In [97]:
id(xt[0])==id(su[0])

True

In [98]:
c ="harshith"

In [99]:
id(c)==id(su)

False