In [1]:
import pandas as pd

In [2]:
df=pd.DataFrame({'col1':[1,2,3,4,5],'col2':[45,56,67,34,34], 'col3':"harshith D rak hem frd".split(), })

In [4]:
"harshith D rak hem frd".split()

['harshith', 'D', 'rak', 'hem', 'frd']

In [7]:
df

col1  col2      col3
0     1    45  harshith
1     2    56         D
2     3    67       rak
3     4    34       hem
4     5    34       frd

In [8]:
df['col4']=df['col1']*df['col1']

In [9]:
df

col1  col2      col3  col4
0     1    45  harshith     1
1     2    56         D     4
2     3    67       rak     9
3     4    34       hem    16
4     5    34       frd    25

In [12]:
df['col5']=df['col3'].str[0]

In [13]:
df

col1  col2      col3  col4 col5
0     1    45  harshith     1    h
1     2    56         D     4    D
2     3    67       rak     9    r
3     4    34       hem    16    h
4     5    34       frd    25    f

In [14]:
def test(a):
    return a**2

In [15]:
df['col4_4']=df['col1'].apply(test)

In [16]:
df

col1  col2      col3  col4 col5  col4_4
0     1    45  harshith     1    h       1
1     2    56         D     4    D       4
2     3    67       rak     9    r       9
3     4    34       hem    16    h      16
4     5    34       frd    25    f      25

In [25]:
def test1(a):
    if a=='h':
        return 'h'
    else:
        return 'z'

In [33]:
df['col6']=df['col5'].apply(test1)

In [34]:
df

col1  col2      col3  col4 col5  col4_4 col6
0     1    45  harshith     1    h       1    h
1     2    56         D     4    D       4    z
2     3    67       rak     9    r       9    z
3     4    34       hem    16    h      16    h
4     5    34       frd    25    f      25    z

In [36]:
df['col6_6']=df['col5'].apply(lambda a:'h' if a=='h' else 'z')

In [37]:
df

col1  col2      col3  col4 col5  col4_4 col6 col6_6
0     1    45  harshith     1    h       1    h      h
1     2    56         D     4    D       4    z      z
2     3    67       rak     9    r       9    z      z
3     4    34       hem    16    h      16    h      h
4     5    34       frd    25    f      25    z      z

In [38]:
df['col7']=df['col3'].apply(len)

In [39]:
df

col1  col2      col3  col4 col5  col4_4 col6 col6_6  col7
0     1    45  harshith     1    h       1    h      h     8
1     2    56         D     4    D       4    z      z     1
2     3    67       rak     9    r       9    z      z     3
3     4    34       hem    16    h      16    h      h     3
4     5    34       frd    25    f      25    z      z     3

In [40]:
import math

In [45]:
df['col8']=df['col2'].apply(math.log)

In [46]:
df

col1  col2      col3  col4 col5  col4_4 col6 col6_6  col7      col8
0     1    45  harshith     1    h       1    h      h     8  3.806662
1     2    56         D     4    D       4    z      z     1  4.025352
2     3    67       rak     9    r       9    z      z     3  4.204693
3     4    34       hem    16    h      16    h      h     3  3.526361
4     5    34       frd    25    f      25    z      z     3  3.526361

In [3]:
#numpy
import numpy as np

In [4]:
 l=["sudh",1,2,3,4]

In [55]:
type(l)

list

In [56]:
np.array(l)

array(['sudh', '1', '2', '3', '4'], dtype='<U11')

In [57]:
type(np.array(l))

numpy.ndarray

In [64]:
a1=np.array([3,4,5,6,3.0])

In [61]:
a=np.array([[1,2],[3,4]])

In [62]:
a

array([[1, 2],
       [3, 4]])

In [63]:
a[1][1]

4

In [65]:
a1

array([3., 4., 5., 6., 3.])

In [66]:
a1[1]

4.0

In [73]:
a2=np.array([1,2,3,4],ndmin=4)

## 

In [74]:
a2

array([[[[1, 2, 3, 4]]]])

In [78]:
a2[0][0][0][0]

1

In [79]:
a

array([[1, 2],
       [3, 4]])

In [80]:
np.asarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [81]:
np.asanyarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [82]:
np.mat([1,2,3,4,5]) #2D is default

matrix([[1, 2, 3, 4, 5]])

In [83]:
a

array([[1, 2],
       [3, 4]])

In [84]:
#matrix is the child class of array

In [85]:
a=[1,2,3,4]

In [86]:
np.asanyarray(a)

array([1, 2, 3, 4])

In [87]:
np.asarray(a)

array([1, 2, 3, 4])

In [88]:
np.mat(a)

matrix([[1, 2, 3, 4]])

In [89]:
np.asanyarray(np.mat(a))

matrix([[1, 2, 3, 4]])

In [90]:
np.fromfunction(lambda i,j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [92]:
np.fromfunction(lambda i, j :i*j, (4,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

In [8]:
a=np.fromfunction(lambda i, j, Z :i*j*Z, (4,3,2),dtype=int)

In [9]:
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [11]:
a.ndim

3

In [12]:
a.size

24

In [13]:
a.shape

(4, 3, 2)

In [14]:
a.dtype

dtype('int32')

In [24]:
#2D
a=np.fromfunction(lambda i, j :i*j, (4,3),dtype=int)

In [17]:
pd.DataFrame(a)

0  1  2
0  0  0  0
1  0  1  2
2  0  2  4
3  0  3  6

In [18]:
np.random.rand(100,4)

array([[0.46869117, 0.88765735, 0.40569464, 0.79811017],
       [0.15631838, 0.11607695, 0.28160042, 0.4326837 ],
       [0.23301666, 0.5998527 , 0.38354239, 0.59516163],
       [0.25395854, 0.50598895, 0.93807482, 0.63197493],
       [0.57962651, 0.58167247, 0.00411607, 0.17391073],
       [0.07330436, 0.65033913, 0.72857686, 0.40152551],
       [0.80321685, 0.42522275, 0.10471291, 0.723446  ],
       [0.5043925 , 0.38229311, 0.1913812 , 0.23934133],
       [0.45362081, 0.67697084, 0.89307866, 0.70039224],
       [0.81794707, 0.13228207, 0.72767593, 0.52569463],
       [0.1091675 , 0.71201987, 0.58652601, 0.03972088],
       [0.34384445, 0.34717865, 0.46144848, 0.50230672],
       [0.54471497, 0.87175754, 0.90018582, 0.69169346],
       [0.93793828, 0.15955205, 0.76111319, 0.3272005 ],
       [0.1060881 , 0.42290923, 0.33418284, 0.4817334 ],
       [0.38714514, 0.09031765, 0.84670991, 0.4531882 ],
       [0.84261174, 0.83727202, 0.0676316 , 0.04088686],
       [0.67778613, 0.37018093,

In [19]:
np.random.randint(4,50)

34

In [23]:
pd.DataFrame(np.random.randn(4,5))

0         1         2         3         4
0 -0.272422  0.349040  1.319326 -0.103675  0.868490
1  0.212745 -0.797088  0.026058 -0.883958 -0.301982
2  1.071080 -1.092791  1.036001  1.646275 -0.097784
3 -1.224088 -1.217787 -0.558640  1.401823 -0.413036

In [25]:
#3d
a=np.fromfunction(lambda i, j, Z :i*j*Z, (4,3,2),dtype=int)

In [29]:
pd.DataFrame(a.reshape(6,4))

0  1  2  3
0  0  0  0  0
1  0  0  0  0
2  0  1  0  2
3  0  0  0  2
4  0  4  0  0
5  0  3  0  6

In [30]:
pd.DataFrame(a.reshape(6,-1))

0  1  2  3
0  0  0  0  0
1  0  0  0  0
2  0  1  0  2
3  0  0  0  2
4  0  4  0  0
5  0  3  0  6

In [31]:
list(range(4,10,.2))

TypeError: 'float' object cannot be interpreted as an integer

In [34]:
a1=np.arange(4,10.5,.2)

In [35]:
a1

array([ 4. ,  4.2,  4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,
        6.2,  6.4,  6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,
        8.4,  8.6,  8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4])

In [37]:
a1[1:4]

array([4.2, 4.4, 4.6])

In [38]:
arr=np.random.rand(4,5)

In [39]:
arr

array([[0.91965995, 0.18494201, 0.51615069, 0.37275703, 0.98424584],
       [0.23014982, 0.27355163, 0.4160139 , 0.75058926, 0.04211062],
       [0.18696046, 0.63453939, 0.15596438, 0.48060247, 0.20200425],
       [0.20358153, 0.50466283, 0.98232961, 0.74412882, 0.35663833]])

In [41]:
arr[arr > .5]

array([0.91965995, 0.51615069, 0.98424584, 0.75058926, 0.63453939,
       0.50466283, 0.98232961, 0.74412882])

In [42]:
arr

array([[0.91965995, 0.18494201, 0.51615069, 0.37275703, 0.98424584],
       [0.23014982, 0.27355163, 0.4160139 , 0.75058926, 0.04211062],
       [0.18696046, 0.63453939, 0.15596438, 0.48060247, 0.20200425],
       [0.20358153, 0.50466283, 0.98232961, 0.74412882, 0.35663833]])

In [43]:
arr[[1,2],[2]]

array([0.4160139 , 0.15596438])

In [45]:
arr = np.random.rand(8,5)

In [46]:
arr

array([[0.97932424, 0.5923086 , 0.86240833, 0.74723932, 0.46925258],
       [0.79026305, 0.83331662, 0.55231928, 0.4241246 , 0.49300809],
       [0.67353991, 0.40341303, 0.43894954, 0.37931957, 0.34532758],
       [0.0232081 , 0.67610981, 0.86698294, 0.71872449, 0.31279847],
       [0.07166851, 0.22986975, 0.88644356, 0.64641142, 0.10959851],
       [0.79707971, 0.0955583 , 0.50135261, 0.12580202, 0.794457  ],
       [0.50067734, 0.93303421, 0.39199521, 0.44355208, 0.17934996],
       [0.99661495, 0.60768677, 0.54412669, 0.0459898 , 0.55532904]])

In [51]:
a2=arr[1:8,0:3]

In [52]:
a2

array([[0.79026305, 0.83331662, 0.55231928],
       [0.67353991, 0.40341303, 0.43894954],
       [0.0232081 , 0.67610981, 0.86698294],
       [0.07166851, 0.22986975, 0.88644356],
       [0.79707971, 0.0955583 , 0.50135261],
       [0.50067734, 0.93303421, 0.39199521],
       [0.99661495, 0.60768677, 0.54412669]])

In [54]:
a2[0,0]=123

In [55]:
a2

array([[1.23000000e+02, 8.33316621e-01, 5.52319282e-01],
       [6.73539913e-01, 4.03413025e-01, 4.38949544e-01],
       [2.32081019e-02, 6.76109812e-01, 8.66982943e-01],
       [7.16685110e-02, 2.29869751e-01, 8.86443561e-01],
       [7.97079714e-01, 9.55582953e-02, 5.01352611e-01],
       [5.00677338e-01, 9.33034207e-01, 3.91995206e-01],
       [9.96614945e-01, 6.07686774e-01, 5.44126692e-01]])

In [59]:
a = np.array([[1,2],[3,4]])
b = np.array([[2,3],[4,5]])

In [60]:
a

array([[1, 2],
       [3, 4]])

In [61]:
b

array([[2, 3],
       [4, 5]])

In [62]:
a*b #elementwise multiplication

array([[ 2,  6],
       [12, 20]])

In [64]:
#matrix Multiplication
m=a@b

In [65]:
m

array([[10, 13],
       [22, 29]])

In [66]:
m/0

C:\Users\Harshith D\AppData\Local\Temp/ipykernel_28196/3791875896.py:1: RuntimeWarning: divide by zero encountered in true_divide
  m/0


array([[inf, inf],
       [inf, inf]])